[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --workspace=server"]

[phases.build]
cmds = ["cd server && npm run build"]

[start]
cmd = "cd server && node dist/index.js"
