name: Deploy Backend to Render

on:
  push:
    branches: [main]
    paths:
      - 'server/**'
      - 'render.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render
        uses: burger/preview-action@v1.2.18
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_BLUEPRINT_ID: exs-dapabdjbc2fs73evq7ng
